### ISSUE TITLE
When zooming images disapears

### ISSUE THREAD

**Issue by PeterJackNaylor** [GeertLitjens/ASAP#23] opened 2017-02-08 15:27 UTC
Hi,

I have been using ASAP for a while, I was able to compile it from source when their was no deb file and now i just install with the deb file and I am currently using ASAP 1.7 (but I had this problem with 1.4) on a ubuntu 16.04 machine.

I have a problem and the source of it is unknown to me. I downloaded from a Phillips scanner, slides that I wish to visualize with ASAP, some files work just fine, but however for many files the image just disappears when I zoom in. 
Here are some visual examples: 

I have loaded my file:

![asapbeforescrol](https://cloud.githubusercontent.com/assets/6742639/22743530/bef58afc-ee1a-11e6-84db-0f3915a4d736.png)
 
and then I just scroll once with my mouse and the tissue is then replaced by black like this:

![asapafterscroll](https://cloud.githubusercontent.com/assets/6742639/22743555/d07fea42-ee1a-11e6-89ae-af8f8ccac084.png)

Wierdly ( ? ), if I analyze the image with some c++ library and rewrite it with vips, I have no issues during the analysis and during the visualization with ASAP. This final point ensures me that it is not a problem with the file but points to maybe some library issues or some compatibility issues.

Any help would be nice as it is super annoying to switch back to windows just to check my slides... (I have had no problem with ASAP under windows tho, for any image)

Thanks,

Peter

**Comment by GeertLitjens** [comment] 2017-02-08 16:07
Hi, thanks for reporting. So first just some checks:

- This behavior is only on Linux or also on Windows?
- If only on Linux, did you compile OpenSlide yourself or do you use the one from the Ubuntu repository?

My first guess is that it is a Philips TIFF file that is for some reason not picked up by OpenSlide but passed to the regular multi-resolution TIFF reader. As an experiment, could you try to open it with the openslide-python bindings directly and see if you can extract image data? Or are you willing in some way to share a slide?

**Comment by PeterJackNaylor** [comment] 2017-02-09 10:36
Hi,

This behavior is only on Linux and I have compiled OpenSlide myself.
I open these files regularly with openslide-python bindings and have had no problem.
Yes I am willing to share the slide, I am sharring a different/smaller slide which you can download from here http://members.cbio.mines-paristech.fr/~pnaylor/Downloads/patient_test.tiff (138 MB).
If you have no issues with the slide under ubuntu I will do a full re installation

I also notice another bug which may be related, but if the images doesn't go black there can be some tiling problems (repeated tiles as you can see in the bellow image, repetition of the cavity in the middle)

![screenshot from 2017-02-09 11-22-57](https://cloud.githubusercontent.com/assets/6742639/22779646/f0892c44-eebb-11e6-891f-fd149daa208d.png)

**Comment by GeertLitjens** [comment] 2017-02-09 14:31
Hi, I checked it on Linux and you are right, there is a viewing problem. I compiled OpenSlide myself as well just to check and I noticed that it is reporting different (i.e. wrong) level dimensions for the TIFF file on Linux.  As the Openslide source is exactly the same, I'm guessing this difference can only be caused by a different libtiff version. 

You can also observe this yourself by using the openslide-show-properties utility on Linux and Windows, it will report wrong dimensions on Linux. As such I would contact the OpenSlide developers as it seems to be a problem on their side.

**Comment by PeterJackNaylor** [comment] 2017-02-09 15:32
Hi,

Sorry I don't fully understand your answer, is it openslide or is it libtiff? 

Under linux and under windows I used openslide-show-properties <filename.tiff>, but the ouputs seem to be the same under both operating system..

**Comment by GeertLitjens** [comment] 2017-02-09 15:49
I get different results on Windows and Linux for the level dimensions for the file you sent me, as reported by openslide-show-properties. That indicates that there is something with openslide. However, as the source code I compiled OpenSlide from should be the same on Windows and Linux, I assume the actual problem is in one of the libraries used by OpenSlide, which are most likely different on Windows and Linux. My guess would be libtiff. However, I cannot easily debug OpenSlide, which is the reason I ams referring you to them.

**Comment by PeterJackNaylor** [comment] 2017-02-09 17:02
Ok, I don't have the same problem with openslide-show-properties as I have just checked and the one under window is identical to the one under linux. Could you show your output files?

I might try installing libtiff again. 
Thanks for your help but as I can't reproduce your error, I will refer them to this issue.

**Comment by GeertLitjens** [comment] 2017-02-09 17:20
Hmm, this is kind of interesting. I turned my Ubuntu virtual machine back on and now the bug is gone, also in the viewer. I can only guess there was a conflict between the openslide I previously installed via apt-get and the one I compiled myself which was resolved by rebooting. At least it seems to have to do with the openslide version. Maybe make sure that you only have one version on your system?

**Comment by GeertLitjens** [comment] 2017-02-13 14:43
Any more info on this bug? Otherwise I will close the issue.

**Comment by PeterJackNaylor** [comment] 2017-02-13 17:48
I haven't had time and uninstalling libtiff was a bad idea. But I guess it is just a installation problem/stability problem as you fixed the problem on the second install.

**Comment by PeterJackNaylor** [comment] 2017-02-17 14:24
Ok, problem has been solved, I didn't touch openslide, but reinstall libtiff did it for me! 
Thanks for the help again

**Closed** 2017-02-17 14:24 UTC
